language: node_js
node_js : 
 - "stable"

script:
   npm install
   npm run build 

deploy:
  provider: surge
  skip_cleanip: true
  domain: chivalrous-chain.surge.sh
  project: /src/build/

  on:
    branch: master